baseURL = "https://pokvful.github.io/"
defaultContentLanguage = "nl"
title = "Portfolio | Tim Meuwsen"
theme = "gokarna"

[params]
avatarURL = "/photo_of_myself.jpg"
avatarSize = "size-l"
accentColor = "#FF4D4D"
socialIcons = [
  { name = "linkedin", url = "https://www.linkedin.com/in/tim-meuwsen-6831aa193/" },
]

footer = "Tim Meuwsen"

[languages]
[languages.en]
contentDir = "content/post/english"
title = "Portfolio | Tim Meuwsen"
languageName = "Translate to English"
weight = 1
description = "Hello ðŸ‘‹ I'm Tim, a 21 year old sofware developer from The Netherlands ðŸ‡³ðŸ‡±"
[languages.en.menu]
[[languages.en.menu.main]]
name = 'Home'
url = '/en'
weight = 1
pre = "<span data-feather='home'></span>"
[[languages.en.menu.main]]
identifier = "about-me"
name = "About"
url = "/en/about-me"
weight = 2
pre = "<span data-feather='user'></span>"
[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/en/projects"
weight = 3
pre = "<span data-feather='code'></span>"
[[languages.en.menu.main]]
identifier = "github"
url = "https://github.com/pokvful"
weight = 4
pre = "<span data-feather='github'></span>"
[languages.nl]
contentDir = "content/post/dutch"
title = "Portfolio | Tim Meuwsen"
languageName = "Vertaal naar Nederlands"
description = "Hallo ðŸ‘‹ Ik ben Tim, 21 jaar en een software developer uit Nederland ðŸ‡³ðŸ‡±"
weight = 2
[languages.nl.menu]
[[languages.nl.menu.main]]
name = 'Home'
url = '/'
weight = 1
pre = "<span data-feather='home'></span>"
[[languages.nl.menu.main]]
name = 'Over mij'
url = '/about-me'
weight = 2
pre = "<span data-feather='user'></span>"
[[languages.nl.menu.main]]
name = 'Projecten'
url = '/projects'
weight = 3
pre = "<span data-feather='code'></span>"
[[languages.nl.menu.main]]
identifier = "github"
url = "https://github.com/pokvful"
weight = 4
pre = "<span data-feather='github'></span>"
